
#+title: Joseph EL HADDAD
#+subtitle: Data Analyst & Scraper

#+OPTIONS: author:nil
#+OPTIONS: \n:t
#+PANDOC_METADATA: geometry:margin=1cm
#+PANDOC_OPTIONS: include-in-header:setup/headers.html:setup/style.css


#+begin_export html
<p class="contact">
<a href="mailto:joseph.ergo@proton.me">joseph.ergo@proton.me</a>
<span class="separator">|</span>
<a target="_blank" rel="noopener" class="pdf-only" href="https://josephelhaddad.github.io">Portfolio</a>
<span class="pdf-only separator">|</span>
<a class="html-only" href="https://drive.google.com/file/d/1Tay9eO6rtB8Zpf_28pSNKoYA4NPrdlnG/view?usp=sharing">Resume PDF</a>
<span class="html-only separator">|</span>
<a href="#">Linked-In</a>
<span class="separator">|</span>
<a href="tel:+212713617633">+212 713-617-633</a>
</p>
<p style="text-align: center;">Available immediately for full/part-time remote roles </p>
#+end_export
* Summary
Versatile and self-taught Data Analyst adept at navigating technical challenges to deliver data-driven intelligence.
Leverages a continuous learning mindset to transform complex information into actionable insights.
* Projects
** Discovery of Google Maps Anomaly
/Independent Data Scraping & Analysis Project/
- First to discover and document a systemic error placing *over 100,000 U.S. businesses* in the ocean during EDA; *~73% shared one coordinate [46.4°N, 129.9°W]*.
- Analysis and visualizations were featured in a blog article [[https://googlemapsmania.blogspot.com/2025/11/american-business-is-all-at-sea.html][GoogleMapsMania - American Business is All at Sea]].
Learn More: [[https://josephelhaddad.github.io/20250109T202901--google-map-plan__note.html#table-of-contents][Link]]
** Large-Scale Talent Intelligence Analysis
/Independent Data Engineering & Analysis Project/
- Engineered a local data pipeline to process and structure *1.4 TB of unstructured data* using DuckDB, enabling the generation of custom reports on company hiring trends, talent networks, and employee career trajectories.

View Example: [[https://josephelhaddad.github.io/reports/metrixlab][Link]]
* Experience
** Data Analyst | Courier Marketing
/Specializing in Data Collection & Web Analytics/

/June 2024 — March 2025/

- Developed automated scripts to audit websites for technical and SEO health, identifying issues like 404 errors, duplicate content, and keyword cannibalization.
- Tracked project progress and communicated insights by presenting findings and proposing new initiatives using Canva.
- Managed end-to-end data collection projects, building targeted contact lists for outreach and aggregating business data for a listing web application.
* Skills
- *Programming & Languages*: Python, R*
- *Data Manipulation & Analysis*: pandas, Polars, DuckDB(SQL*)
- *Data Visualization*: Matplotlib, Plotly, ggplot2*
- *Web Scraping & Automation*: requests, Beautiful Soup, Selenium
- *Computer Vision & Automation*: OpenCV, Pillow
- *Software & Tools*: Microsoft Excel, Google sheets, Canva, Emacs
- *Operating Systems*: Debian (Linux), Windows
- *Core Practices*: Data Privacy, Security-Conscious

* Education
** Independent, Self-Directed Study
/2016 — Present & Future/
- Continuously enhancing data analysis and engineering skills through online resources and hands-on project work.


#+begin_export html
<h1 class="html-only">Portfolio Analytics</h1>
<iframe data-external="1" class="html-only looker-report" src="https://lookerstudio.google.com/embed/reporting/acbdd3a4-e607-44f2-be33-5e0b07dd4a7a/page/h8PjF" frameborder="0" style="border:0" allowfullscreen sandbox="allow-storage-access-by-user-activation allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox"></iframe>
#+end_export
