
#+title: Joseph EL HADDAD
#+subtitle: Data analyst/scraper

#+OPTIONS: author:nil
#+OPTIONS: \n:t
#+PANDOC_METADATA: geometry:margin=1cm



#+BEGIN_HTML
<style>
body {max-width: 50em;}
.title {
font-size: xxx-large;
font-weight: bold;
}
  
.subtitle {
font-size: x-large;
font-weight: bold;
}
h2{
margin-left: 0.5rem;
}

@media print {
h1, h2 {
page-break-after: avoid;
}
}

.contact {text-align: center; margin-top:-2rem}
.contact a {
white-space: nowrap;
display: inline-block;
}
@media print {
.contact {
break-inside: avoid
}
}


html {
scroll-behavior: smooth;
}

body {
/* High-quality typography for the whole resume */
text-wrap: pretty; 
}

@media print {
/* Prevent sections from splitting across PDF pages */
section, .job-item {
break-inside: avoid;
}
  
/* Keep headers on the same page as their sub-content */
h1, h2 {
break-after: avoid;
}
}


</style>
#+END_HTML

#+begin_export html
<p class="contact">
<a href="mailto:joseph.ergo@proton.me">joseph.ergo@proton.me</a> |
<a href="https://josephelhaddad.github.io">Portfolio</a> |
<a href="https://linkedin.com/in/yourprofile">LinkedIn</a> |
<a href="tel:+212713617633">+212 713-617-633</a>
</p>
<p style="text-align: center;"> Available immediately for full/part-time remote roles </p>
#+end_export

* Summary
Versatile and self-taught Data Analyst adept at navigating technical challenges to deliver data-driven intelligence.
Leverages a continuous learning mindset to transform complex information into actionable insights.
* Projects
** Discovery of Google Maps Anomaly
/Independent Data Scraping & Analysis Project/
- First to discover and document a systemic error placing *over 100,000 U.S. businesses* in the ocean during EDA; *~73% shared one coordinate [46.4°N, 129.9°W]*.
- Analysis and visualizations were featured in a blog article [[https://googlemapsmania.blogspot.com/2025/11/american-business-is-all-at-sea.html][GoogleMapsMania - American Business is All at Sea]].
More in my post: [[https://josephelhaddad.github.io/20250109T202901--google-map-plan__note.html#table-of-contents][Link]]
** Large-Scale Talent Intelligence Analysis
/Independent Data Engineering & Analysis Project/
- Engineered a local data pipeline to process and structure *1.4 TB of unstructured data* using DuckDB, enabling the generation of custom reports on company hiring trends, talent networks, and employee career trajectories.

Report example: [[https://josephelhaddad.github.io/reports/metrixlab][Link]]
* Experience
** Data Analyst | Courier Marketing
/Specializing in Data Collection & Web Analytics/

/June 2024 — March 2025/

- Developed automated scripts to audit websites for technical and SEO health, identifying issues like 404 errors, duplicate content, and keyword cannibalization.
- Tracked project progress and communicated insights by presenting findings and proposing new initiatives using Canva.
- Managed end-to-end data collection projects, building targeted contact lists for outreach and aggregating business data for a listing web application.
* Skills
- *Programming & Languages*: Python, R
- *Data Manipulation & Analysis*: pandas, Polars, DuckDB(SQL*)
- *Data Visualization*: Matplotlib, Plotly, ggplot2*
- *Web Scraping & Automation*: requests, Beautiful Soup, Selenium
- *Computer Vision & Automation*: OpenCV, Pillow
- *Software & Tools*: Microsoft Excel, Google sheets, Canva, Emacs
- *Operating Systems*: Debian (Linux), Windows
- *Core Practices*: Data Privacy, Security-Conscious

* Education
** Independent, Self-Directed Study
/2016 — Present & Future/
- Continuously enhancing data analysis and engineering skills through online resources and hands-on project work.
